config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  get '/mentions-legales' => 'pages#mentions'
  get '/expertise' => 'pages#domaines'
  get '/valeurs' => 'pages#valeurs'

  resources :actualites
  resources :equipes
  resources :cabinets, only: [:index]
  resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actualite.rb
class Actualite < ApplicationRecord
  validates :title, presence: true
  validates :contenu, presence: true
  validates :auteur, presence: true
  validates :day, presence: true
  validates :month, presence: true
  validates :year, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :titre, presence: true
  validates :date, presence: true
  validates :auteur, presence: true
  validates :description, presence: true

end

app/models/cabinet.rb
class Cabinet < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/contact.rb
class Contact < MailForm::Base


  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :telephone
  attribute :message
  attribute :nickname,  :captcha  => true



  def headers
    {
      :subject => "Formulaire de contact",
      :to => "david.crenin@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/equipe.rb
class Equipe < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :bio, presence: true
  validates :engagement, presence: true
  validates :name, presence: true
  validates :fonction, presence: true
  validates :photo, presence: true
  validates :formation, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/actualites_controller.rb
class ActualitesController < ApplicationController
  before_action :set_actualite, only: [:show, :edit, :update, :destroy]

  def index
    @actualites = Actualite.all
  end

  def show
  end

  def new
    @actualite = Actualite.new
  end

  def create
    @actualite = Actualite.create(actualite_params)
    respond_to do |format|
      if @actualite.save
        format.html { redirect_to @actualite, notice: "Un nouvel article vient d'être ajouté !" }
        format.json { render action: 'show', status: :created, location: @actualite }
      else
        format.html { render action: 'new' }
        format.json { render json: @actualite.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @actualite.update(actualite_params)
        format.html { redirect_to @actualite, notice: "Un nouvel article vient d'être ajouté !" }
        format.json { render action: 'show', status: :created, location: @actualite }
      else
        format.html { render action: 'edit' }
        format.json { render json: @actualite.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @actualite.destroy
    redirect_to actualites_path
  end



    private

  def set_actualite
    @actualite = Actualite.find(params[:id])
  end

  def actualite_params
    params.require(:actualite).permit(:title, :auteur, :contenu, :day, :month, :year)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController
  def index

    @cabinets = Cabinet.where.not(latitude: nil, longitude: nil)
    @markers = @cabinets.map do |cabinet|
      {
        lng: cabinet.longitude,
        lat: cabinet.latitude
      }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Merci pour votre message !'
      redirect_to root_path
    else
      flash.now[:error] = "Le message n'a pas pu être envoyé. Veuillez réessayer."
      render :new
    end
  end

end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
   before_action :set_equipe, only: [:show, :edit, :update, :destroy]

  def index
    @equipes = Equipe.all
  end

  def show
  end

  def new
    @equipe = Equipe.new
  end

  def create
    @equipe = Equipe.create(equipe_params)
    respond_to do |format|
      if @equipe.save
        format.html { redirect_to @equipe, notice: "Un nouvel article vient d'être ajouté !" }
        format.json { render action: 'show', status: :created, location: @equipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @equipe.update(equipe_params)
        format.html { redirect_to @equipe, notice: "Un nouvel article vient d'être ajouté !" }
        format.json { render action: 'show', status: :created, location: @equipe }
      else
        format.html { render action: 'edit' }
        format.json { render json: @equipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @equipe.destroy
    redirect_to equipes_path
  end



    private

  def set_equipe
    @equipe = Equipe.find(params[:id])
  end

  def equipe_params
    params.require(:equipe).permit(:name, :photo, :bio, :formation, :engagement, :fonction, :linkedin, :email)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @contact = Contact.new
    @actualites = Actualite.all
  end

  def mentions
  end

  def domaines
  end

  def valeurs
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actualites/edit.html.erb
 <div class="container container-margin">
  <h1>Modifier une publication</h1>

<div class="row">
  <div class="col-md-12">
<%= simple_form_for(@actualite, :html => { multipart: true }) do |f| %>
 <% if @actualite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actualite.errors.count, "erreur") %> empêchent l'objet d'être ajouté:</h2>

      <ul>
      <% @actualite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-form">
    <div class="champs">
      <%= f.input :title, label: "Titre de l'article" %>
      <%= f.input :contenu, label: "Contenu de l'article" %>
    <div class="row">
      <div class="col-xs-4 margin-padding-null">
        <%= f.input :day, label: 'Jour de publication', collection: 01..31, prompt: "Sélectionner un jour" %>
      </div>
      <div class="col-xs-4 margin-padding-null">
        <%= f.input :month, label: 'Mois de publication', collection: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"], prompt: "Sélectionner un mois" %>
      </div>
      <div class="col-xs-4 margin-padding-null">
        <%= f.input :year, label: 'Année de publication', collection: 2019..2025, prompt: "Sélectionner une année", selected: 2019 %>
      </div>
    </div>
      <%= f.input :auteur, label: 'Auteur de la publication' %>
    </div>

    <div class="actions btn-margin">
      <%= f.button :submit, 'Valider' %>
    </div>
    <% end %>

<p><%= link_to "RETOUR AUX ANNONCES", actualites_path, class: 'link-form'  %></p>
  </div>

     </div>
</div>
</div>

app/views/actualites/index.html.erb
<div class="actu-container">
  <%= image_tag 'banner3.jpg' %>
</div>
<div class="actu-index-container">
  <div class="container">


  <div class="navigation">
  <%= link_to "Accueil", '/' %>  <% if user_signed_in? %> / <%= link_to 'Ajouter une publication', new_actualite_path  %> <% end %>

  </div>

  <div data-aos="fade-left"
    data-aos-offset="400"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true" class="text-center">

  <h1>Nos dernières actualités</h1>
  <%= image_tag 'quote.svg' %>
  </div>

  <div class="container" data-aos="fade-up-left"
    data-aos-offset="200"
    data-aos-delay="500"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">
    <% @actualites.each do |actualite| %>
  <div class="row">
    <div class="col-xs-12 col-md-3 date-border">
      <div class="date"><%= actualite.day %></div>
      <span class="month"><%= actualite.month %></span> <br>
      <span class="year"><%= actualite.year %></span>
    </div>
    <div class="col-xs-12 col-md-9 article-border article-position">
      <h2><%= actualite.title %></h2>
      <h6>Ecrit par : <%= actualite.auteur %></h6>
      <p><%= actualite.contenu %></p>
      <%= link_to "Lire la suite", actualite_path(actualite)  %>
    </div>
  </div>
  <% end %>
  </div>


</div>

</div>

<script>
    AOS.init();
  </script>

app/views/actualites/new.html.erb
 <div class="container container-margin">
  <h1>Créer une publication</h1>

<div class="row">
  <div class="col-md-12">
<%= simple_form_for(@actualite, :html => { multipart: true }) do |f| %>
 <% if @actualite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actualite.errors.count, "erreur") %> empêchent l'objet d'être ajouté:</h2>

      <ul>
      <% @actualite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-form">
    <div class="champs">
      <%= f.input :title, label: "Titre de l'article" %>
      <%= f.input :contenu, label: "Contenu de l'article" %>
    <div class="row">
      <div class="col-xs-4 margin-padding-null">
        <%= f.input :day, label: 'Jour de publication', collection: 01..31, prompt: "Sélectionner un jour" %>
      </div>
      <div class="col-xs-4 margin-padding-null">
        <%= f.input :month, label: 'Mois de publication', collection: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"], prompt: "Sélectionner un mois" %>
      </div>
      <div class="col-xs-4 margin-padding-null">
        <%= f.input :year, label: 'Année de publication', collection: 2019..2025, prompt: "Sélectionner une année", selected: 2019 %>
      </div>
    </div>
      <%= f.input :auteur, label: 'Auteur de la publication' %>
    </div>

    <div class="actions btn-margin">
      <%= f.button :submit, 'Valider' %>
    </div>
    <% end %>

<p><%= link_to "RETOUR AUX ANNONCES", actualites_path, class: 'link-form'  %></p>
  </div>

     </div>
</div>
</div>

app/views/actualites/show.html.erb
<div class="actu-container">
  <%= image_tag 'banner3.jpg' %>
</div>
<div class="actu-index-container">
<div class="container">
  <div class="navigation">
    <%= link_to "Editer la publication", edit_actualite_path  %> / <%= link_to "Supprimer la publication", actualite_path(@actualite), :method => :delete  %>
  </div>

  <div class="container">
    <div data-aos="fade-left"
    data-aos-offset="400"
    data-aos-delay="5000"
    data-aos-duration="3000"
    data-aos-easing="ease-in-out"
    data-aos-once="true" class="text-center">

  <h1>Nos dernières actualités</h1>
  <%= image_tag 'quote.svg' %>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-5 date-border">
      <div class="date"><%= @actualite.day %></div>
      <span class="month"><%= @actualite.month %></span> <br>
      <span class="year"><%= @actualite.year %></span>
    </div>
    <div class="col-xs-12 col-md-6 article-border">
      <h2><%= @actualite.title %></h2>
      <h6>Ecrit par : <%= @actualite.auteur %></h6>
      <p><%= @actualite.contenu %></p>
    </div>
  </div>

  </div>
</div>
</div>
<script>
    AOS.init();
  </script>

app/views/cabinets/index.html.erb
<div id="mapCanvas" style="width: 1000px; height: 1000px"></div>
<button class="button type1">
    Effect one
  </button>

app/views/contacts/new.html.erb
<div class="container ">
<div class="row">
  <div class="col-xs-12">
  <div id="mapCanvas" style="width: auto; height: 300px; margin-top: 50px;"></div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-md-4 contact-coordonnees">
    <h2>Cabinet 107 Université</h2>
    <p>107 rue de l'université</p>
    <p>75007</p>

    <p>Tél: 01 54 54 54 54</p>
    <p>Email: contact@107universite.com</p>
  </div>
  <div class="col-xs-12 col-md-8 form-container">
  <div class="row">
          <h2>Nous contacter</h2>
  <div class="row contac">
  <%= simple_form_for @contact do |f| %>
  <div class="row col-xs-12">
    <%= f.input :name, label: 'Votre nom (obligatoire)', :required => true, :input_html => {:class => 'input-style'} %>

  </div>
  <div class="row col-xs-12">
    <%= f.input :email, label: 'Votre adresse email (obligatoire)',:required => true, :input_html => {:class => 'input-style'} %>

  </div>
  <div class="row col-xs-12">
    <%= f.input :telephone, label: 'Votre téléphone (obligatoire)',:required => true, :input_html => {:class => 'input-style'} %>

  </div>
  <div class="row col-xs-12">
    <%= f.input :message, label: 'Votre message (obligatoire)',:required => true, :as => :text, :required => false, :input_html => {:rows => 5, :class => 'input-style'} %>

  </div>
    <div class="form-actions">
    <div class="hidden">
    <%= f.input :nickname %>
    </div>

      <button class="button type1"><%= f.button :submit, 'Envoyer', class: 'border-top-color' %> </button>
      <br><br>

    </div>
  <% end %>

  </div>



  </div>

<div class="footer-form">
  <p><em>*Les informations communiquées sont destinées à la société éditrice de ce site. Vous bénéficiez d'un droit d'accès, de modification, de rectification et de suppression de vos données personnelles (Loi n°2004-575 du 21 juin 2004 pour la confiance dans l'économie numérique). Pour les exercer, adressez-vous à l'adresse de l'Editeur.</em></p>

</div>
  </div>
</div>


</div>

app/views/equipes/index.html.erb
<div class="equipe-container">
  <div class="container container-equipe">
    <div class="navigation">
      <h6><%= link_to "Accueil", '/'  %> / L'Equipe <% if user_signed_in? %> / <%= link_to "Ajouter un nouveau membre", new_equipe_path  %> <% end %></h6>
    </div>
    <div class="header-equipe text-center" data-aos="fade-left"
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">
      <h1 data-aos="fade-left"
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">Notre Equipe</h1>
      <%= image_tag 'team.svg' %>
      <p data-aos="fade-right"
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">Notre équipe se compose d’avocats choisis pour leurs qualités académiques et
leur aptitude à écouter, conseiller et défendre dans un environnement exigeant.

Diplômés d’universités françaises et étrangères et de grandes écoles, nos avocats
travaillent indistinctement en français et en anglais.

Nous accordons une place essentielle à la formation continue. Nos avocats
s’astreignent chaque année à des sessions de perfectionnement et de remise à niveau,
afin de garantir à nos clients une sécurité juridique de premier plan.</p>
    </div>
    <% @equipes.each do |equipe| %>
    <div class="row">
      <%= link_to equipe_path(equipe) do %>
      <div class="col-xs-12 col-sm-6 col-md-3 contain">
        <div class="photo-container image " style= "background-image: url('<%= cl_image_path equipe.photo, height: 200, crop: :fill %>')">
      </div>
          <div class="card-text middle">
            <div class="text-equipe">
            <h3><%= equipe.name %></h3>
            <h6><%= equipe.fonction %></h6>

            </div>
          </div>
        </div>
  <% end %>
  <% end %>
    </div>
  </div>
</div>

<script>
    AOS.init();
  </script>

app/views/equipes/show.html.erb
<div class="equipe-container">
  <div class="container container-equipe">
    <div class="navigation cool-link">
      <%= link_to 'Accueil', '/'  %> / <%= link_to "Equipe", equipes_path  %> <% if user_signed_in? %> / <%= link_to "Modifier la biographie", edit_equipe_path(@equipe) %> / <%= link_to "Supprimer cette biographie", equipe_path(@equipe), method: :delete  %> <% end %>
    </div>
    <div class="header-equipe text-center">
      <%= image_tag 'team.svg' %>
      <h2><%= @equipe.name %></h2>
      <h4><%= @equipe.fonction %></h4>
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-4">
          <div class="photo-container" style= "background-image: url('<%= cl_image_path @equipe.photo, height: 200, crop: :fill %>')">
          </div>
        </div>
        <div class="col-xs-12 col-md-7">
          <p><%= simple_format(h @equipe.bio)  %></p>
        </div>
      </div>
      <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-4 formation">
          <h2>Formation</h2>
          <% if @equipe.formation.present? %>
          <p><%= simple_format(h @equipe.formation) %></p>
          <% else %>
            <p>Ces informations ne sont pas précisées.</p>
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 engagement">
          <h2>Engagements</h2>
            <% if @equipe.engagement.present? %>
              <p><%= simple_format(h @equipe.engagement) %></p>
              <% else %>
              <p>Ces informations ne sont pas précisées.</p>
            <% end %>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 engagement">
          <h2>Contact</h2>
          <div class="inline">
            <% if @equipe.email.present? %>
              <%= image_tag 'email.svg' %>  <%= simple_format(h @equipe.email) %>
              <% else %>
              <p> Non précisé</p>
            <% end %>


          </div>
          <div class="inline">
            <% if @equipe.linkedin.present? %>
              <%= image_tag 'linkedin.svg' %> <a href="#{<%= simple_format(h @equipe.linkedin) %>}"></a>
              <% else %>
              <p> Non précisé</p>
            <% end %>


          </div>
        </div>
      </div>

  </div>
</div>

app/views/pages/domaines.html.erb
<div class="domaine-container-index">

</div>

app/views/pages/home.html.erb
	<div class="home-container">
	  <div class="banner-container">
	 <ul class="rslides" id="slider2">
	  <li class="img-slider1"></li>
	  <li class="img-slider2"></li>
	  <li class="img-slider3"></li>

	</ul>
	</div>
  <div class="presentation-cabinet-background">
  <div class="container">



	<div class="cabinet-description" data-aos="zoom-in"
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">
	  <div class="row">
      <div class="col-xs-12 col-md-6 logo-cabinet">
	     <h1><%= image_tag 'logo.svg' %></h1> <!-- <hr class="style-one"></hr> -->

      </div>


	      <div class="col-xs-12 col-md-6 text-description">
	      <p>
	    On sait depuis longtemps que travailler avec du texte lisible et contenant du sens est source de distractions, et empêche de se concentrer sur la mise en page elle-même. L'avantage du Lorem Ipsum sur un texte générique comme 'Du texte. Du texte. Du texte.' est qu'il possède une distribution de lettres plus ou moins normale, et en tout cas comparable avec celle du français standard. De nombreuses suites logicielles de mise en page ou éditeurs de sites Web ont fait du Lorem Ipsum leur faux texte par défaut, et une recherche pour 'Lorem Ipsum' vous conduira vers de nombreux sites qui n'en sont encore qu'à leur phase de construction. Plusieurs versions sont apparues avec le temps, parfois par accident, souvent intentionnellement (histoire d'y rajouter de petits clins d'oeil, voire des phrases embarassantes).
	  </p>
	    </div>
	  </div>
    </div>
	</div>
  </div>
	<div class="domaine-container">
	  <div class="container">


	  <h1 class="text-center">Domaines d'expertise</h1>
	  <div class="row">
	    <div class="col-xs-12 col-sm-6 col-md-3 card"data-aos="zoom-in"
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true" >
	      <h2 >Droit Social</h2>
	    </div><div class="col-xs-12 col-sm-6 col-md-3 card"data-aos="zoom-in
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">
	      <h2>Contentieux</h2>
	    </div><div class="col-xs-12 col-sm-6 col-md-3 card"data-aos="zoom-in"
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">
	      <h2>Droit d'information</h2>
	    </div><div class="col-xs-12 col-sm-6 col-md-3 card"data-aos="zoom-in
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">
	      <h2>Droit de l'environnement</h2>
	    </div>
	  </div>
	  </div>
	</div>
  <% if @actualites.count > 1  %>
  <div class="actualite-container-background">

	<div class="container news-container">
	  <div class="text-center">
	  <h1>Nos Actualités</h1>
	  <%= image_tag 'quote.svg' %>
	  </div>

	  <% @actualites.each do |actualite| %>

	  <div class="row">
	    <div class="col-xs-12 col-md-4 article" data-aos="zoom-in"
    data-aos-offset="200"
    data-aos-delay="5000"
    data-aos-duration="1000"
    data-aos-easing="ease-in-out"
    data-aos-once="true">
	      <div class="article-position">
	        <%= image_tag 'edit.svg' %>
	      <h4><%= h truncate(actualite.title, :length => 40) %></h4>
	      <h6><%= actualite.day %>/ <%= actualite.month %>/<%= actualite.year %> - <%= actualite.auteur %></h6>
	      <p><%=h truncate(actualite.contenu, :length => 280) %></p>
	      <%= link_to "Lire la suite", actualite_path(actualite)  %>

	      </div>
	    </div>

      <% end %>
	</div>
	<div class="text-center">
	  <%= link_to "Voir toutes les publications", actualites_path, class: "btn-all"  %>
	  </div>
</div>
</div>
<% else %>

<% end %>
</div>
</div>


<script>
$(function () {
   $("#slider2").responsiveSlides({
        auto: true,
        pager: false,
        nav: false,
        speed: 2000,
        timeout: 5000,
        namespace: "transparent-btns"
      });
    });
</script>
<script>
    AOS.init();
  </script>

app/views/pages/mentions.html.erb
  <div class="container">
    <div class="textes-container">


    </div>

  </div>

app/views/pages/valeurs.html.erb
<h1>Valeurs de l'entreprise</h1>

app/views/shared/_footer.html.erb
<footer class="section bg-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="">
                        <h3 class="footer-heading text-uppercase text-white">Navigation</h3>
                        <ul class="list-unstyled footer-link mt-4">
                            <li><%= link_to "Accueil", '/'  %></li>
                            <li><%= link_to "Expertise", '/'  %></li>
                            <li><%= link_to "Equipe", equipes_path %></li>
                            <li><%= link_to "Actualités", actualites_path  %></li>
                              <% if user_signed_in? %>
        <li><%= link_to "Déconnexion", destroy_user_session_path  %></li>
        <% else %>
        <li><%= link_to "Admin", new_user_session_path  %></li>
        <% end %>
                        </ul>
                    </div>
                </div>



                <div class="col-lg-4">
                    <div class="">
                        <h3 class="footer-heading text-uppercase text-white">Informations</h3>
                        <ul class="list-unstyled footer-link mt-4">
                            <li><% if user_signed_in? %>
        <li><%= link_to "Déconnexion", destroy_user_session_path  %></li>
        <% else %>
        <li><%= link_to "Admin", new_user_session_path  %></li></li>
                            <% end %>
                            <li><%= link_to "Mentions legales", mentions_legales_path  %></li>

                        </ul>
                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="">
                        <h3 class="footer-heading text-uppercase text-white">Contact</h3>
                        <p class="contact-info mt-4">N'hésitez pas à nous contacter pour toutes informations.</p>
                        <p class="contact-info">Tél: 01 45 45 45 45</p>
                        <p class="contact-info">E-mail: contact@107universites.com</p>
                        <%= link_to "Formulaire de contact", new_contact_path, class:'btn-contact'  %>

                    </div>
                </div>

            </div>
        </div>

        <div class="text-center mt-5">
            <p class="footer-alt mb-0 f-14">2019 © 107universités, Tous droits réservés</p>
        </div>
    </footer>

app/views/shared/_navbar.html.erb
  <div class="nav-bar-container">
   <div class="logo-container">
    <a href="/" ><%= image_tag "logo.svg", id: "logo" %></a>

  </div>


    <div class="link-primary">
        <ul class="nav navbar-nav hidden-xs hidden-sm">
          <li><%= link_to "Accueil", '/'  %></li>
            <li><%= link_to "Equipe", equipes_path  %></li>
                <li><%= link_to 'Expertise', expertise_path   %></li>
                <li><%= link_to "Actualites", actualites_path %></li>
                <li><%= link_to "Contact", new_contact_path %></li>

        </ul>

  <div class="hamburger hidden-md  hidden-lg btn-open" id="hamburger-12">
          <span class="line"></span>
          <span class="line"></span>
          <span class="line"></span>
          <span class="letter">MENU</span>
        </div>

</div>

<div class="overlay">
  <div class="wrap">
    <ul class="wrap-nav">
      <ul>
        <li><%= link_to "Equipe", equipes_path  %></li>
                <li><%= link_to 'Expertise', expertise_path   %></li>
                <li><%= link_to "Actualites", actualites_path %></li>
                <li><%= link_to "Contact", new_contact_path %></li>
      <li><%= link_to "Mentions legales", mentions_legales_path %></li>
      </ul>
      </li>
    </ul>
  </div>
</div>
</div>